version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # usually we map port 80 of the container to port 80 of the host
    environment:
      # here we set the environment variables for the database connection
      # these should be taken from fmi
      - DB_HOST=10.10.108.51
      - DB_PORT=3306
      - DB_NAME=coin_collector_db
      - DB_USER=user
      - DB_PASSWORD=password
    volumes:
      - ./uploads:/var/www/html/uploads  # this maps the uploads directory on the host to the uploads directory in the container
    restart: unless-stopped