-- Auto-generated countries data
INSERT IGNORE INTO countries (name, iso_code_2, iso_code_3, continent, flag_image) VALUES 
('Antigua and Barbuda', 'AG', 'ATG', 'North America', 'https://flagcdn.com/w320/ag.png'),
('Bhutan', 'BT', 'BTN', 'Asia', 'https://flagcdn.com/w320/bt.png'),
('Italy', 'IT', 'ITA', 'Europe', 'https://flagcdn.com/w320/it.png'),
('Tuvalu', 'TV', 'TUV', 'Oceania', 'https://flagcdn.com/w320/tv.png'),
('Anguilla', 'AI', 'AIA', 'North America', 'https://flagcdn.com/w320/ai.png'),
('Australia', 'AU', 'AUS', 'Oceania', 'https://flagcdn.com/w320/au.png'),
('Belize', 'BZ', 'BLZ', 'North America', 'https://flagcdn.com/w320/bz.png'),
('Vanuatu', 'VU', 'VUT', 'Oceania', 'https://flagcdn.com/w320/vu.png'),
('Belarus', 'BY', 'BLR', 'Europe', 'https://flagcdn.com/w320/by.png'),
('Mauritius', 'MU', 'MUS', 'Africa', 'https://flagcdn.com/w320/mu.png'),
('Laos', 'LA', 'LAO', 'Asia', 'https://flagcdn.com/w320/la.png'),
('Senegal', 'SN', 'SEN', 'Africa', 'https://flagcdn.com/w320/sn.png'),
('Turkey', 'TR', 'TUR', 'Europe', 'https://flagcdn.com/w320/tr.png'),
('Bolivia', 'BO', 'BOL', 'South America', 'https://flagcdn.com/w320/bo.png'),
('Sri Lanka', 'LK', 'LKA', 'Asia', 'https://flagcdn.com/w320/lk.png'),
('Norfolk Island', 'NF', 'NFK', 'Oceania', 'https://flagcdn.com/w320/nf.png'),
('China', 'CN', 'CHN', 'Asia', 'https://flagcdn.com/w320/cn.png'),
('Caribbean Netherlands', 'BQ', 'BES', 'North America', 'https://flagcdn.com/w320/bq.png'),
('Guernsey', 'GG', 'GGY', 'Europe', 'https://flagcdn.com/w320/gg.png'),
('Sudan', 'SD', 'SDN', 'Africa', 'https://flagcdn.com/w320/sd.png'),
('Mayotte', 'YT', 'MYT', 'Africa', 'https://flagcdn.com/w320/yt.png'),
('Saint Barthélemy', 'BL', 'BLM', 'North America', 'https://flagcdn.com/w320/bl.png'),
('Vatican City', 'VA', 'VAT', 'Europe', 'https://flagcdn.com/w320/va.png'),
('Turks and Caicos Islands', 'TC', 'TCA', 'North America', 'https://flagcdn.com/w320/tc.png'),
('Curaçao', 'CW', 'CUW', 'North America', 'https://flagcdn.com/w320/cw.png'),
('Botswana', 'BW', 'BWA', 'Africa', 'https://flagcdn.com/w320/bw.png'),
('Benin', 'BJ', 'BEN', 'Africa', 'https://flagcdn.com/w320/bj.png'),
('Lithuania', 'LT', 'LTU', 'Europe', 'https://flagcdn.com/w320/lt.png'),
('Montserrat', 'MS', 'MSR', 'North America', 'https://flagcdn.com/w320/ms.png'),
('British Virgin Islands', 'VG', 'VGB', 'North America', 'https://flagcdn.com/w320/vg.png'),
('Burundi', 'BI', 'BDI', 'Africa', 'https://flagcdn.com/w320/bi.png'),
('United States Minor Outlying Islands', 'UM', 'UMI', 'Oceania', 'https://flagcdn.com/w320/um.png'),
('Ireland', 'IE', 'IRL', 'Europe', 'https://flagcdn.com/w320/ie.png'),
('Solomon Islands', 'SB', 'SLB', 'Oceania', 'https://flagcdn.com/w320/sb.png'),
('Bermuda', 'BM', 'BMU', 'North America', 'https://flagcdn.com/w320/bm.png'),
('Finland', 'FI', 'FIN', 'Europe', 'https://flagcdn.com/w320/fi.png'),
('Peru', 'PE', 'PER', 'South America', 'https://flagcdn.com/w320/pe.png'),
('Bangladesh', 'BD', 'BGD', 'Asia', 'https://flagcdn.com/w320/bd.png'),
('Denmark', 'DK', 'DNK', 'Europe', 'https://flagcdn.com/w320/dk.png'),
('Saint Vincent and the Grenadines', 'VC', 'VCT', 'North America', 'https://flagcdn.com/w320/vc.png'),
('Dominican Republic', 'DO', 'DOM', 'North America', 'https://flagcdn.com/w320/do.png'),
('Moldova', 'MD', 'MDA', 'Europe', 'https://flagcdn.com/w320/md.png'),
('Bulgaria', 'BG', 'BGR', 'Europe', 'https://flagcdn.com/w320/bg.png'),
('Costa Rica', 'CR', 'CRI', 'North America', 'https://flagcdn.com/w320/cr.png'),
('Namibia', 'NA', 'NAM', 'Africa', 'https://flagcdn.com/w320/na.png'),
('Svalbard and Jan Mayen', 'SJ', 'SJM', 'Europe', 'https://flagcdn.com/w320/sj.png'),
('Luxembourg', 'LU', 'LUX', 'Europe', 'https://flagcdn.com/w320/lu.png'),
('Russia', 'RU', 'RUS', 'Europe', 'https://flagcdn.com/w320/ru.png'),
('United Arab Emirates', 'AE', 'ARE', 'Asia', 'https://flagcdn.com/w320/ae.png'),
('Sint Maarten', 'SX', 'SXM', 'North America', 'https://flagcdn.com/w320/sx.png'),
('Bahamas', 'BS', 'BHS', 'North America', 'https://flagcdn.com/w320/bs.png'),
('Japan', 'JP', 'JPN', 'Asia', 'https://flagcdn.com/w320/jp.png'),
('Nigeria', 'NG', 'NGA', 'Africa', 'https://flagcdn.com/w320/ng.png'),
('Ghana', 'GH', 'GHA', 'Africa', 'https://flagcdn.com/w320/gh.png'),
('Sierra Leone', 'SL', 'SLE', 'Africa', 'https://flagcdn.com/w320/sl.png'),
('Saint Pierre and Miquelon', 'PM', 'SPM', 'North America', 'https://flagcdn.com/w320/pm.png'),
('Albania', 'AL', 'ALB', 'Europe', 'https://flagcdn.com/w320/al.png'),
('Tokelau', 'TK', 'TKL', 'Oceania', 'https://flagcdn.com/w320/tk.png'),
('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 'Africa', 'https://flagcdn.com/w320/sh.png'),
('Tonga', 'TO', 'TON', 'Oceania', 'https://flagcdn.com/w320/to.png'),
('Turkmenistan', 'TM', 'TKM', 'Asia', 'https://flagcdn.com/w320/tm.png'),
('Djibouti', 'DJ', 'DJI', 'Africa', 'https://flagcdn.com/w320/dj.png'),
('Central African Republic', 'CF', 'CAF', 'Africa', 'https://flagcdn.com/w320/cf.png'),
('Lebanon', 'LB', 'LBN', 'Asia', 'https://flagcdn.com/w320/lb.png'),
('Latvia', 'LV', 'LVA', 'Europe', 'https://flagcdn.com/w320/lv.png'),
('Cocos (Keeling) Islands', 'CC', 'CCK', 'Asia', 'https://flagcdn.com/w320/cc.png'),
('Gambia', 'GM', 'GMB', 'Africa', 'https://flagcdn.com/w320/gm.png'),
('Honduras', 'HN', 'HND', 'North America', 'https://flagcdn.com/w320/hn.png'),
('Niue', 'NU', 'NIU', 'Oceania', 'https://flagcdn.com/w320/nu.png'),
('Mauritania', 'MR', 'MRT', 'Africa', 'https://flagcdn.com/w320/mr.png'),
('Kosovo', 'XK', 'UNK', 'Europe', 'https://flagcdn.com/w320/xk.png'),
('Wallis and Futuna', 'WF', 'WLF', 'Oceania', 'https://flagcdn.com/w320/wf.png'),
('South Georgia', 'GS', 'SGS', 'Antarctica', 'https://flagcdn.com/w320/gs.png'),
('French Polynesia', 'PF', 'PYF', 'Oceania', 'https://flagcdn.com/w320/pf.png'),
('Togo', 'TG', 'TGO', 'Africa', 'https://flagcdn.com/w320/tg.png'),
('Belgium', 'BE', 'BEL', 'Europe', 'https://flagcdn.com/w320/be.png'),
('Zambia', 'ZM', 'ZMB', 'Africa', 'https://flagcdn.com/w320/zm.png'),
('Cayman Islands', 'KY', 'CYM', 'North America', 'https://flagcdn.com/w320/ky.png'),
('Pitcairn Islands', 'PN', 'PCN', 'Oceania', 'https://flagcdn.com/w320/pn.png'),
('Cook Islands', 'CK', 'COK', 'Oceania', 'https://flagcdn.com/w320/ck.png'),
('Madagascar', 'MG', 'MDG', 'Africa', 'https://flagcdn.com/w320/mg.png'),
('Montenegro', 'ME', 'MNE', 'Europe', 'https://flagcdn.com/w320/me.png'),
('South Korea', 'KR', 'KOR', 'Asia', 'https://flagcdn.com/w320/kr.png'),
('Ethiopia', 'ET', 'ETH', 'Africa', 'https://flagcdn.com/w320/et.png'),
('Mongolia', 'MN', 'MNG', 'Asia', 'https://flagcdn.com/w320/mn.png'),
('Slovakia', 'SK', 'SVK', 'Europe', 'https://flagcdn.com/w320/sk.png'),
('Cuba', 'CU', 'CUB', 'North America', 'https://flagcdn.com/w320/cu.png'),
('Antarctica', 'AQ', 'ATA', 'Antarctica', 'https://flagcdn.com/w320/aq.png'),
('Guatemala', 'GT', 'GTM', 'North America', 'https://flagcdn.com/w320/gt.png'),
('French Guiana', 'GF', 'GUF', 'South America', 'https://flagcdn.com/w320/gf.png'),
('Norway', 'NO', 'NOR', 'Europe', 'https://flagcdn.com/w320/no.png'),
('Grenada', 'GD', 'GRD', 'North America', 'https://flagcdn.com/w320/gd.png'),
('Réunion', 'RE', 'REU', 'Africa', 'https://flagcdn.com/w320/re.png'),
('Chile', 'CL', 'CHL', 'South America', 'https://flagcdn.com/w320/cl.png'),
('Colombia', 'CO', 'COL', 'South America', 'https://flagcdn.com/w320/co.png'),
('Saudi Arabia', 'SA', 'SAU', 'Asia', 'https://flagcdn.com/w320/sa.png'),
('Israel', 'IL', 'ISR', 'Asia', 'https://flagcdn.com/w320/il.png'),
('Germany', 'DE', 'DEU', 'Europe', 'https://flagcdn.com/w320/de.png'),
('New Zealand', 'NZ', 'NZL', 'Oceania', 'https://flagcdn.com/w320/nz.png'),
('Greenland', 'GL', 'GRL', 'North America', 'https://flagcdn.com/w320/gl.png'),
('Kyrgyzstan', 'KG', 'KGZ', 'Asia', 'https://flagcdn.com/w320/kg.png'),
('El Salvador', 'SV', 'SLV', 'North America', 'https://flagcdn.com/w320/sv.png'),
('Faroe Islands', 'FO', 'FRO', 'Europe', 'https://flagcdn.com/w320/fo.png'),
('Palau', 'PW', 'PLW', 'Oceania', 'https://flagcdn.com/w320/pw.png'),
('Malta', 'MT', 'MLT', 'Europe', 'https://flagcdn.com/w320/mt.png'),
('Syria', 'SY', 'SYR', 'Asia', 'https://flagcdn.com/w320/sy.png'),
('Timor-Leste', 'TL', 'TLS', 'Oceania', 'https://flagcdn.com/w320/tl.png'),
('Croatia', 'HR', 'HRV', 'Europe', 'https://flagcdn.com/w320/hr.png'),
('Papua New Guinea', 'PG', 'PNG', 'Oceania', 'https://flagcdn.com/w320/pg.png'),
('Netherlands', 'NL', 'NLD', 'Europe', 'https://flagcdn.com/w320/nl.png'),
('Liberia', 'LR', 'LBR', 'Africa', 'https://flagcdn.com/w320/lr.png'),
('Somalia', 'SO', 'SOM', 'Africa', 'https://flagcdn.com/w320/so.png'),
('Venezuela', 'VE', 'VEN', 'South America', 'https://flagcdn.com/w320/ve.png'),
('Haiti', 'HT', 'HTI', 'North America', 'https://flagcdn.com/w320/ht.png'),
('Algeria', 'DZ', 'DZA', 'Africa', 'https://flagcdn.com/w320/dz.png'),
('Northern Mariana Islands', 'MP', 'MNP', 'Oceania', 'https://flagcdn.com/w320/mp.png'),
('Saint Martin', 'MF', 'MAF', 'North America', 'https://flagcdn.com/w320/mf.png'),
('Heard Island and McDonald Islands', 'HM', 'HMD', 'Antarctica', 'https://flagcdn.com/w320/hm.png'),
('Aruba', 'AW', 'ABW', 'North America', 'https://flagcdn.com/w320/aw.png'),
('Egypt', 'EG', 'EGY', 'Africa', 'https://flagcdn.com/w320/eg.png'),
('Malawi', 'MW', 'MWI', 'Africa', 'https://flagcdn.com/w320/mw.png'),
('Equatorial Guinea', 'GQ', 'GNQ', 'Africa', 'https://flagcdn.com/w320/gq.png'),
('United States Virgin Islands', 'VI', 'VIR', 'North America', 'https://flagcdn.com/w320/vi.png'),
('Ecuador', 'EC', 'ECU', 'South America', 'https://flagcdn.com/w320/ec.png'),
('Uzbekistan', 'UZ', 'UZB', 'Asia', 'https://flagcdn.com/w320/uz.png'),
('Gabon', 'GA', 'GAB', 'Africa', 'https://flagcdn.com/w320/ga.png'),
('South Sudan', 'SS', 'SSD', 'Africa', 'https://flagcdn.com/w320/ss.png'),
('Iran', 'IR', 'IRN', 'Asia', 'https://flagcdn.com/w320/ir.png'),
('Kazakhstan', 'KZ', 'KAZ', 'Asia', 'https://flagcdn.com/w320/kz.png'),
('Nicaragua', 'NI', 'NIC', 'North America', 'https://flagcdn.com/w320/ni.png'),
('Iceland', 'IS', 'ISL', 'Europe', 'https://flagcdn.com/w320/is.png'),
('Slovenia', 'SI', 'SVN', 'Europe', 'https://flagcdn.com/w320/si.png'),
('Guadeloupe', 'GP', 'GLP', 'North America', 'https://flagcdn.com/w320/gp.png'),
('Cameroon', 'CM', 'CMR', 'Africa', 'https://flagcdn.com/w320/cm.png'),
('Argentina', 'AR', 'ARG', 'South America', 'https://flagcdn.com/w320/ar.png'),
('Azerbaijan', 'AZ', 'AZE', 'Europe', 'https://flagcdn.com/w320/az.png'),
('Uganda', 'UG', 'UGA', 'Africa', 'https://flagcdn.com/w320/ug.png'),
('Niger', 'NE', 'NER', 'Africa', 'https://flagcdn.com/w320/ne.png'),
('Christmas Island', 'CX', 'CXR', 'Asia', 'https://flagcdn.com/w320/cx.png'),
('Myanmar', 'MM', 'MMR', 'Asia', 'https://flagcdn.com/w320/mm.png'),
('Poland', 'PL', 'POL', 'Europe', 'https://flagcdn.com/w320/pl.png'),
('Jordan', 'JO', 'JOR', 'Asia', 'https://flagcdn.com/w320/jo.png'),
('Hong Kong', 'HK', 'HKG', 'Asia', 'https://flagcdn.com/w320/hk.png'),
('DR Congo', 'CD', 'COD', 'Africa', 'https://flagcdn.com/w320/cd.png'),
('Eritrea', 'ER', 'ERI', 'Africa', 'https://flagcdn.com/w320/er.png'),
('Kiribati', 'KI', 'KIR', 'Oceania', 'https://flagcdn.com/w320/ki.png'),
('Marshall Islands', 'MH', 'MHL', 'Oceania', 'https://flagcdn.com/w320/mh.png'),
('Burkina Faso', 'BF', 'BFA', 'Africa', 'https://flagcdn.com/w320/bf.png'),
('Zimbabwe', 'ZW', 'ZWE', 'Africa', 'https://flagcdn.com/w320/zw.png'),
('Kenya', 'KE', 'KEN', 'Africa', 'https://flagcdn.com/w320/ke.png'),
('Comoros', 'KM', 'COM', 'Africa', 'https://flagcdn.com/w320/km.png'),
('Gibraltar', 'GI', 'GIB', 'Europe', 'https://flagcdn.com/w320/gi.png'),
('Brunei', 'BN', 'BRN', 'Asia', 'https://flagcdn.com/w320/bn.png'),
('Sweden', 'SE', 'SWE', 'Europe', 'https://flagcdn.com/w320/se.png'),
('Lesotho', 'LS', 'LSO', 'Africa', 'https://flagcdn.com/w320/ls.png'),
('Isle of Man', 'IM', 'IMN', 'Europe', 'https://flagcdn.com/w320/im.png'),
('Micronesia', 'FM', 'FSM', 'Oceania', 'https://flagcdn.com/w320/fm.png'),
('Tanzania', 'TZ', 'TZA', 'Africa', 'https://flagcdn.com/w320/tz.png'),
('Cape Verde', 'CV', 'CPV', 'Africa', 'https://flagcdn.com/w320/cv.png'),
('Afghanistan', 'AF', 'AFG', 'Asia', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png'),
('Andorra', 'AD', 'AND', 'Europe', 'https://flagcdn.com/w320/ad.png'),
('Greece', 'GR', 'GRC', 'Europe', 'https://flagcdn.com/w320/gr.png'),
('Vietnam', 'VN', 'VNM', 'Asia', 'https://flagcdn.com/w320/vn.png'),
('French Southern and Antarctic Lands', 'TF', 'ATF', 'Antarctica', 'https://flagcdn.com/w320/tf.png'),
('Iraq', 'IQ', 'IRQ', 'Asia', 'https://flagcdn.com/w320/iq.png'),
('Libya', 'LY', 'LBY', 'Africa', 'https://flagcdn.com/w320/ly.png'),
('Portugal', 'PT', 'PRT', 'Europe', 'https://flagcdn.com/w320/pt.png'),
('Pakistan', 'PK', 'PAK', 'Asia', 'https://flagcdn.com/w320/pk.png'),
('Maldives', 'MV', 'MDV', 'Asia', 'https://flagcdn.com/w320/mv.png'),
('Morocco', 'MA', 'MAR', 'Africa', 'https://flagcdn.com/w320/ma.png'),
('Bosnia and Herzegovina', 'BA', 'BIH', 'Europe', 'https://flagcdn.com/w320/ba.png'),
('Samoa', 'WS', 'WSM', 'Oceania', 'https://flagcdn.com/w320/ws.png'),
('Palestine', 'PS', 'PSE', 'Asia', 'https://flagcdn.com/w320/ps.png'),
('Oman', 'OM', 'OMN', 'Asia', 'https://flagcdn.com/w320/om.png'),
('Bahrain', 'BH', 'BHR', 'Asia', 'https://flagcdn.com/w320/bh.png'),
('United States', 'US', 'USA', 'North America', 'https://flagcdn.com/w320/us.png'),
('Puerto Rico', 'PR', 'PRI', 'North America', 'https://flagcdn.com/w320/pr.png'),
('British Indian Ocean Territory', 'IO', 'IOT', 'Asia', 'https://flagcdn.com/w320/io.png'),
('Jersey', 'JE', 'JEY', 'Europe', 'https://flagcdn.com/w320/je.png'),
('North Macedonia', 'MK', 'MKD', 'Europe', 'https://flagcdn.com/w320/mk.png'),
('Tunisia', 'TN', 'TUN', 'Africa', 'https://flagcdn.com/w320/tn.png'),
('Trinidad and Tobago', 'TT', 'TTO', 'North America', 'https://flagcdn.com/w320/tt.png'),
('Estonia', 'EE', 'EST', 'Europe', 'https://flagcdn.com/w320/ee.png'),
('Singapore', 'SG', 'SGP', 'Asia', 'https://flagcdn.com/w320/sg.png'),
('Panama', 'PA', 'PAN', 'North America', 'https://flagcdn.com/w320/pa.png'),
('Switzerland', 'CH', 'CHE', 'Europe', 'https://flagcdn.com/w320/ch.png'),
('Uruguay', 'UY', 'URY', 'South America', 'https://flagcdn.com/w320/uy.png'),
('Tajikistan', 'TJ', 'TJK', 'Asia', 'https://flagcdn.com/w320/tj.png'),
('Taiwan', 'TW', 'TWN', 'Asia', 'https://flagcdn.com/w320/tw.png'),
('South Africa', 'ZA', 'ZAF', 'Africa', 'https://flagcdn.com/w320/za.png'),
('Liechtenstein', 'LI', 'LIE', 'Europe', 'https://flagcdn.com/w320/li.png'),
('Brazil', 'BR', 'BRA', 'South America', 'https://flagcdn.com/w320/br.png'),
('Armenia', 'AM', 'ARM', 'Asia', 'https://flagcdn.com/w320/am.png'),
('Georgia', 'GE', 'GEO', 'Asia', 'https://flagcdn.com/w320/ge.png'),
('Åland Islands', 'AX', 'ALA', 'Europe', 'https://flagcdn.com/w320/ax.png'),
('Qatar', 'QA', 'QAT', 'Asia', 'https://flagcdn.com/w320/qa.png'),
('Dominica', 'DM', 'DMA', 'North America', 'https://flagcdn.com/w320/dm.png'),
('Ukraine', 'UA', 'UKR', 'Europe', 'https://flagcdn.com/w320/ua.png'),
('Guinea', 'GN', 'GIN', 'Africa', 'https://flagcdn.com/w320/gn.png'),
('Macau', 'MO', 'MAC', 'Asia', 'https://flagcdn.com/w320/mo.png'),
('Western Sahara', 'EH', 'ESH', 'Africa', 'https://flagcdn.com/w320/eh.png'),
('Czechia', 'CZ', 'CZE', 'Europe', 'https://flagcdn.com/w320/cz.png'),
('Austria', 'AT', 'AUT', 'Europe', 'https://flagcdn.com/w320/at.png'),
('Saint Kitts and Nevis', 'KN', 'KNA', 'North America', 'https://flagcdn.com/w320/kn.png'),
('Saint Lucia', 'LC', 'LCA', 'North America', 'https://flagcdn.com/w320/lc.png'),
('Yemen', 'YE', 'YEM', 'Asia', 'https://flagcdn.com/w320/ye.png'),
('Rwanda', 'RW', 'RWA', 'Africa', 'https://flagcdn.com/w320/rw.png'),
('Monaco', 'MC', 'MCO', 'Europe', 'https://flagcdn.com/w320/mc.png'),
('São Tomé and Príncipe', 'ST', 'STP', 'Africa', 'https://flagcdn.com/w320/st.png'),
('Republic of the Congo', 'CG', 'COG', 'Africa', 'https://flagcdn.com/w320/cg.png'),
('Paraguay', 'PY', 'PRY', 'South America', 'https://flagcdn.com/w320/py.png'),
('Bouvet Island', 'BV', 'BVT', 'Antarctica', 'https://flagcdn.com/w320/bv.png'),
('Mozambique', 'MZ', 'MOZ', 'Africa', 'https://flagcdn.com/w320/mz.png'),
('France', 'FR', 'FRA', 'Europe', 'https://flagcdn.com/w320/fr.png'),
('Eswatini', 'SZ', 'SWZ', 'Africa', 'https://flagcdn.com/w320/sz.png'),
('Barbados', 'BB', 'BRB', 'North America', 'https://flagcdn.com/w320/bb.png'),
('Spain', 'ES', 'ESP', 'Europe', 'https://flagcdn.com/w320/es.png'),
('Thailand', 'TH', 'THA', 'Asia', 'https://flagcdn.com/w320/th.png'),
('Guinea-Bissau', 'GW', 'GNB', 'Africa', 'https://flagcdn.com/w320/gw.png'),
('Angola', 'AO', 'AGO', 'Africa', 'https://flagcdn.com/w320/ao.png'),
('India', 'IN', 'IND', 'Asia', 'https://flagcdn.com/w320/in.png'),
('Martinique', 'MQ', 'MTQ', 'North America', 'https://flagcdn.com/w320/mq.png'),
('New Caledonia', 'NC', 'NCL', 'Oceania', 'https://flagcdn.com/w320/nc.png'),
('Seychelles', 'SC', 'SYC', 'Africa', 'https://flagcdn.com/w320/sc.png'),
('Falkland Islands', 'FK', 'FLK', 'South America', 'https://flagcdn.com/w320/fk.png'),
('United Kingdom', 'GB', 'GBR', 'Europe', 'https://flagcdn.com/w320/gb.png'),
('Fiji', 'FJ', 'FJI', 'Oceania', 'https://flagcdn.com/w320/fj.png'),
('San Marino', 'SM', 'SMR', 'Europe', 'https://flagcdn.com/w320/sm.png'),
('Mali', 'ML', 'MLI', 'Africa', 'https://flagcdn.com/w320/ml.png'),
('Canada', 'CA', 'CAN', 'North America', 'https://flagcdn.com/w320/ca.png'),
('Jamaica', 'JM', 'JAM', 'North America', 'https://flagcdn.com/w320/jm.png'),
('Nauru', 'NR', 'NRU', 'Oceania', 'https://flagcdn.com/w320/nr.png'),
('Indonesia', 'ID', 'IDN', 'Asia', 'https://flagcdn.com/w320/id.png'),
('Guam', 'GU', 'GUM', 'Oceania', 'https://flagcdn.com/w320/gu.png'),
('Ivory Coast', 'CI', 'CIV', 'Africa', 'https://flagcdn.com/w320/ci.png'),
('Kuwait', 'KW', 'KWT', 'Asia', 'https://flagcdn.com/w320/kw.png'),
('Philippines', 'PH', 'PHL', 'Asia', 'https://flagcdn.com/w320/ph.png'),
('Guyana', 'GY', 'GUY', 'South America', 'https://flagcdn.com/w320/gy.png'),
('Hungary', 'HU', 'HUN', 'Europe', 'https://flagcdn.com/w320/hu.png'),
('Mexico', 'MX', 'MEX', 'North America', 'https://flagcdn.com/w320/mx.png'),
('North Korea', 'KP', 'PRK', 'Asia', 'https://flagcdn.com/w320/kp.png'),
('Romania', 'RO', 'ROU', 'Europe', 'https://flagcdn.com/w320/ro.png'),
('Suriname', 'SR', 'SUR', 'South America', 'https://flagcdn.com/w320/sr.png'),
('American Samoa', 'AS', 'ASM', 'Oceania', 'https://flagcdn.com/w320/as.png'),
('Nepal', 'NP', 'NPL', 'Asia', 'https://flagcdn.com/w320/np.png'),
('Chad', 'TD', 'TCD', 'Africa', 'https://flagcdn.com/w320/td.png'),
('Serbia', 'RS', 'SRB', 'Europe', 'https://flagcdn.com/w320/rs.png'),
('Cambodia', 'KH', 'KHM', 'Asia', 'https://flagcdn.com/w320/kh.png'),
('Malaysia', 'MY', 'MYS', 'Asia', 'https://flagcdn.com/w320/my.png'),
('Cyprus', 'CY', 'CYP', 'Europe', 'https://flagcdn.com/w320/cy.png');